# Generated by Django 3.0.5 on 2022-01-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='public',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
