# Generated by Django 3.0.5 on 2022-01-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter_app', '0003_public_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='user',
        ),
    ]
